name = "given"
version = "6.0.2"
description = "👇 Ergonomic guards aka early returns for Bool, Result, Option, and List types in Gleam!"
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-given" }

gleam = ">= 1.15.4"

[documentation]
pages = [
  { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
  { title = "LICENSE", path = "license.html", source = "LICENSE" },
]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.10.0 and < 2.0.0"
